### ISSUE TITLE
How to use train.sh

### ISSUE THREAD

**Issue by NDG-2018** [xcyao00/BGAD#2]
When I run "python main.py --flow_arch conditional_flow_model --gpu 0 --data_path /my/dateset/path --with_fas --data_strategy 0,1 --num_anomalies 10 --not_in_test --exp_name bgad_fas_10 --focal_weighting --pos_beta 0.01 --margin_tau 0.1"

It's appear error is that "ValueError: operands could not be broadcast together with shapes (900,900,3) (900,900)"

**Comment by NDG-2018** [comment]
and "ValueError: Caught ValueError in DataLoader worker process 0."

**Comment by xcyao00** [comment]
Can you give me the detailed error line? This error may occurr in the dataset codes.

**Comment by NDG-2018** [comment]
ye,the details as:
Traceback (most recent call last):
  File "D:\pycharm\projects\BGAD-main\main.py", line 70, in <module>
    main()
  File "D:\pycharm\projects\BGAD-main\main.py", line 57, in main
    img_auc, pix_auc, pix_pro = main_single(args)
  File "D:\pycharm\projects\BGAD-main\main.py", line 31, in main_single
    img_auc, pix_auc, pix_pro = train(args)
  File "D:\pycharm\projects\BGAD-main\engines\bgad_fas_train_engine.py", line 227, in train
    train_meta_epoch(args, epoch, [normal_loader, train_loader], encoder, decoders, optimizer)
  File "D:\pycharm\projects\BGAD-main\engines\bgad_fas_train_engine.py", line 32, in train_meta_epoch
    for i, (data) in enumerate(tqdm(data_loader)):
  File "D:\Anaconda\anaconda\envs\pytorch_gpu\lib\site-packages\tqdm\std.py", line 1178, in __iter__
    for obj in iterable:
  File "D:\Anaconda\anaconda\envs\pytorch_gpu\lib\site-packages\torch\utils\data\dataloader.py", line 681, in __next__
    data = self._next_data()
  File "D:\Anaconda\anaconda\envs\pytorch_gpu\lib\site-packages\torch\utils\data\dataloader.py", line 1376, in _next_data
    return self._process_data(data)
  File "D:\Anaconda\anaconda\envs\pytorch_gpu\lib\site-packages\torch\utils\data\dataloader.py", line 1402, in _process_data
    data.reraise()
  File "D:\Anaconda\anaconda\envs\pytorch_gpu\lib\site-packages\torch\_utils.py", line 461, in reraise
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\pycharm\projects\BGAD-main\datasets\mvtec.py", line 318, in __getitem__
    img, mask = self.copy_paste(img, mask)
  File "D:\pycharm\projects\BGAD-main\datasets\mvtec.py", line 387, in copy_paste
    intersect_mask = np.logical_and(fg_mask == 255, aug_mask == 255)
ValueError: operands could not be broadcast together with shapes (900,900,3) (900,900)

**Comment by Ehteshamciitwah** [comment]
Hello, I face the same problem did you solve it?
To achieve the paper performance. Could you share detail about these parameters in config file?
 data_strategy,num_anomalies,anomaly_source_path,in_fg_region,balanced_data_loader. Thank you

**Comment by Ehteshamciitwah** [comment]
@NDG-2018 i solved the problem. the problem was in mvtec dataloader copy_paste function. Modify the fg_mask line according to your directory.  
https://github.com/xcyao00/BGAD/blob/054517771d12877ff029b3c5a3814f200fffb698/datasets/mvtec.py#L380

**Comment by NDG-2018** [comment]
> With your help, it has just been adjusted. Thank you very much

**Comment by NDG-2018** [comment]
@Ehteshamciitwah With your help, it has just been adjusted. Thank you very much.

**Comment by flyingtiger111** [comment]
> @NDG-2018 i solved the problem. the problem was in mvtec dataloader copy_paste function. Modify the fg_mask line according to your directory.
> 
> https://github.com/xcyao00/BGAD/blob/054517771d12877ff029b3c5a3814f200fffb698/datasets/mvtec.py#L380

Can you give a more detailed solution? I am facing the same problem.

**Comment by aron456** [comment]
> @NDG-2018 i solved the problem. the problem was in mvtec dataloader copy_paste function. Modify the fg_mask line according to your directory.
> 
> https://github.com/xcyao00/BGAD/blob/054517771d12877ff029b3c5a3814f200fffb698/datasets/mvtec.py#L380

Can you explain it in detail ? I also face this problem,thankyou.

**Comment by aron456** [comment]
> > @NDG-2018 i solved the problem. the problem was in mvtec dataloader copy_paste function. Modify the fg_mask line according to your directory.
> > https://github.com/xcyao00/BGAD/blob/054517771d12877ff029b3c5a3814f200fffb698/datasets/mvtec.py#L380
> 
> Can you give a more detailed solution? I am facing the same problem.

hello,Have you solved it? How did you do it?

**Comment by aron456** [comment]
> @Ehteshamciitwah With your help, it has just been adjusted. Thank you very much.

Hello, how did you do it?Can you give a more detailed solution?thank you

**Comment by aron456** [comment]
@NDG-2018 Hello, how did you do it?Can you give a more detailed solution?thank you

**Comment by aron456** [comment]
@flyingtiger111  hello,Have you solved it? How did you do it?

**Comment by aron456** [comment]
@Ehteshamciitwah Can you explain it in detail ? I also face this problem,thankyou.
